### ISSUE TITLE
Status of wakanda/  company

### ISSUE THREAD

**Issue by vegarringdal** [Wakanda/wakanda-issues#145]
Hi

I would like to try and use wakanda again, but I kinda feel its not very active/ open.
Ive said it many times I like the database, but would have been more motivating trying to use it again if we knew more on whats going on.

Who is on the team, whos doing what ?

Why not use github as the source for the server source, so we would actually see some beta branch get a lot of activity etc  (yes I know Ive asked about this before)

What is the status of business/economy 2016 compared to 2016 ? Will you end up as the next rethinkdb and just close the doors?

I also think the blog should be more of what you are working on, some faq about the server and how to solve them etc

Will you kill WAF/prototyper in th 2.0 beta, and focus more on the server/backend features ? I think that would be smart, so may good frameworks out there, ember, angular, aurelia, vue. why use resources on something you can use to improve the core of the product, the db/restapi/server.

**Comment by dellsmash** [comment]
I would say the front end is very tightly bound to the server in rpc, database and widget actions.  I can easily see how the prototype element can be sidestepped but the open version has no connector to mysql or any other db the world uses so using just the server at this point does not add much value to the world of web application design.  I use wakanda because of the fast design time for connections from widgets to records in a db.  when you are building a web app with 15 or 20 pages total and 25 or 30 tables in your database any website should be fast and hand coding the front end wont be a problem.  In my world the applications have hundreds of pages and link to more than a dozen databases simultaneously, every byte counts, I have found no problems memory or cpu on the server, the client experience is tough to get just right here though.

**Comment by vegarringdal** [comment]
@dellsmash, well Im only at the open source version :-)
so you use the enterprise to get and save data to other databases then, does the selection and orderby work then, or build from selection?

how many users at once/hardware?

what about the other stuff, like better blogs, github source of server.

**Comment by dellsmash** [comment]
I have been testing Wakanda threw the different versions and yes the enterprise version.  rpc call or xhr to the server, run the query generation and data grab then send the object back to the browser for a .sync() to the datasource, not a task for the faint of heart.  Datasources will .sync() in the browser but at a huge cost, use sparingly, widgets work as expected.  I have only tested 20 connected users, not a large test but the server does not seem to blink an eye at 12,000 requests an hour.  I actually ran a test to dump data into mysql and believe it or not the mysql server threw up its hands before the wakanda server... something like 36 gigs of data sent to mysql...

**Comment by vegarringdal** [comment]
Got some answers here 👍 @hamzahik 
https://gitter.im/wakandasoft/Lobby?at=588b6064fba5bfea06963ed0

Ill close this for now, and hope after release of 2.0, the blog changes focus to connect with community, and maybe gitlab repos are made more open to view, how to build etc.

@dellsmash 
I dont use enterprise, but if you could tell me how the entityset part and selection of the rest API works when working with remote sources then that would be great.
Sounds really good that it server is stable, is the requests to the server http or just the database?
What CPU and RAM size is the wakanda db running on.
Do you not use the internal database for storage?
