### ISSUE TITLE
4D Server crashes on project method call

### ISSUE THREAD

**Issue by JUX84** [Wakanda/wakanda-issues#153]
Hello,

I have an issue with 4D project methods.
When used on a 4D Client with a HTTP server running, it works perfectly, but when it's a 4D Server, the server crashes right when I call the method. While scanning with Wireshark I can see that the server doesn't even have the time to send a response.

![screen shot 2017-02-15 at 4 39 45 pm](https://cloud.githubusercontent.com/assets/3422399/22982357/3d4b0ea2-f39f-11e6-832d-5ee2395e8dc9.png)

The bug appears only when calling methods, because querying data from the 4D server doesn't crash or anything.

I don't know if the issue is on 4D side, or Wakanda side, or maybe even both sides.

Regards.

**Comment by liuxiang625** [comment]
Hi Jux84,

It appears your issue is related to 4D server and 4D Mobile since the crashing is happening within 4D.

There are dedicated support resources for 4D and 4D Mobile in [4D TAOW](taow.4d.com) system. You can create a case and get support to resolve the crashing of 4D server.  If you are in a region where 4D TAOW is not available. Please contact your account rep and file a 4D support case with the support platform serving your region.

Regards.

**Comment by JUX84** [comment]
Yes,

After discussing with @hamzahik  on gitter, I asked my boss to file a report on TAOW, just forgot to close the issue here :p

Regards.
