### ISSUE TITLE
Invalid Document Structure - New Project

### ISSUE THREAD

**Issue by AlistairBates** [Wakanda/wakanda-issues#236]
I created a new application (backend only) on Mac. 
Tar'ed the entire project directory.
Transferred to an Ubuntu server and expanded.
Tried to start wakanda server with this project on Ubuntu and got the following errors.

2018-01-10 17:17:34 [wakanda.waktest3.backend.xmlc] ERROR - [3] invalid document structure, task #1196, task name is Wakanda Server
2018-01-10 17:17:34 [wakanda.waktest3.backend.xmlc] ERROR - [3] invalid document structure, task #1196, task name is Wakanda Server
2018-01-10 17:17:34 [wakanda.waktest3.backend.iasv] ERROR - [1019] Cannot load the settings files, task #1196, task name is Wakanda Server
2018-01-10 17:17:34 [wakanda.waktest3.backend] WARN - "backend" project opened with errors
2018-01-10 17:17:34 [wakanda.waktest3.iasv] ERROR - [1013] Cannot open 'backend' project, task #1196, task name is Wakanda Server
2018-01-10 17:17:34 [wakanda.waktest3.backend] INFO - "backend" project closed

Wakanda Studio 2.3.0
Wakanda Community Server  2.3.0
Ubuntu 17.10

**Comment by hamzahik** [comment]
Hi @AlistairBates,

When you say you tar'ed the project, you mean the Wakanda solution, right ?

When you open the settings file of the project and the solution using VI or VIM what do you see ?

**Comment by AlistairBates** [comment]
Hi @hamzahik 

Yes - mean the solution directory, sorry.

Both the settings files look OK. I can't see anything wrong with them.

When I say I created a new application, I did nothing else but create the application. I didn't modify any of the files. I just opened Wakanda Studio, created a new project then tried to get it to run on Ubuntu.

I have uploaded a copy of the project here. [https://github.com/AlistairBates/waktest](url)

**Comment by JegoYann** [comment]
Hello @AlistairBates ,
This `waktest/.wakanda` repo is missing. It cannot be open in a Wakanda Studio. However, this is probably not why your are experimenting your issue.

Your solution is working without `invalid document structure` errors on Ubuntu 16.04.

Here is a `tar` command that is working correctly for me. I was able to tar a simple (unmodified) backend solution, untar it on ubuntu 16.04 and run it on Wakanda Server 2.3.0.

```
tar cz -f "./Untitled13.tgz" ./Untitled13
```

Could be related to Ubuntu 17.10.
Do you reproduce on Ubuntu 16.04 ?

**Comment by AlistairBates** [comment]
Hi @JegoYann,

The problem is with the .wakanda folder. My solution uploaded on github does not have hidden folders uploaded.  I have attached the actual tar I made that is having trouble. 

This solution is not running on Ubuntu 16.04 or 17.10 as is.

If I delete the backend/.wakanda folder it runs. 

I only use wakanda studio to initially create the project and do not use it for development so this workaround will be fine for me.

Is there any documentation at all for the scaffolding of wakanda solutions?

[waktest3.tar.gz](https://github.com/Wakanda/wakanda-issues/files/1640977/waktest3.tar.gz)

**Comment by JegoYann** [comment]
Still, `watktest3.tar.gz` is working correctly on Ubuntu 16.04. I don't see any `invalid document structure` issue.

Sorry, no documentation about Wakanda scaffolding. For now, the `.wakanda` folder is for studio usage only. You can safely remove it from your solution if you are not using the studio.

`invalid document structure` + `Cannot load the settings files` means that is project `waSettings` is invalid. Did you update it ? Is it valid xml ?

**Comment by AlistairBates** [comment]
> Did you update it ? Is it valid xml ?

No I didn't change it.It's exactly what you see in the tar file. See my comment from previously.

> When I say I created a new application, I did nothing else but create the application. I didn't modify any of the files. I just opened Wakanda Studio, created a new project then tried to get it to run on Ubuntu.

**Comment by hamzahik** [comment]
@AlistairBates you should also check the permissions and owner of your files.

**Comment by AlistairBates** [comment]
@hamzahik It took 13 days to tell me to check the permissions and owners of the files? Wow. It's actually got nothing to do with that.

It has to do with bsdtar generating files with ' ._*' for files that are archived and have extended information. If I delete these files it runs correctly.

If I can make a few suggestions.

1. Stop changing the scaffolding, and document what it is at the moment. It seems like every version released has moved project files around and there is still no documentation. It seems like adding a hidden folder (.wakanda) and not mentioning it anywhere was a bit of a mistake.

2. When @JegoYann said

> Here is a tar command that is working correctly for me. I was able to tar a simple (unmodified) backend solution, untar it on ubuntu 16.04 and run it on Wakanda Server 2.3.0.

Did he do this from a Mac?

3. I'm not an idiot. Telling me 13 days later to check file permissions is a waste of your time and mine.

**Comment by hamzahik** [comment]
Hi @AlistairBates,

Sorry we couldn't help you more efficiently.

As you know this is free support and we do what we can to help users as quickly as possible. If you have a support contract please use the correct communication channels and you will have quicker answers and we usually ask for direct access to the client's machine using ssh to debug the problem in the user's environment.

We have helped many of our users with these kind of problems and a lot of them are Windows users deploying on Linux and they are not familiar with permissions/owners.. we don't assume the user is familiar with Linux otherwise we miss obvious issues and waste time of users/clients.

Breaking changes happen only on major versions and this is when the scaffolding changed(from v1 to v2). If you detect a breaking change that happened on a minor or patch release that would be a bug and we have an internal process to prevent this from happening.

@JegoYann used tar on macOS (tar is a link to bsdtar) the difference might be on the Ubuntu side(filesystem support for extended attributes enabled/disabled, the tar command used to unpack the file default ubuntu tar (gnu) or bsdtar package? ...)

![image](https://user-images.githubusercontent.com/6703912/36198197-35ff400a-1176-11e8-90e7-e38f1af89b03.png)
https://discussions.apple.com/thread/3145071
