### ISSUE TITLE
Wakanda Server not starting with systemctl command

### ISSUE THREAD

**Issue by AlistairBates** [Wakanda/wakanda-issues#243]
### Current Behaviour

After installation, running the command 

<pre>
sudo systemctl start wakanda
</pre>

does not start the wakanda server

The command 

<pre>
sudo systemctl status wakanda
</pre>

Shows the service as running.

### Expected Behaviour

After running the command the server should start

### Environment

Ubuntu 17.10 x64
Wakanda Server 2.4.0

(The command is starting the server on Ubuntu 16.04)

**Comment by erlicthemad** [comment]
I have found that is kind of problem show up most often if there is a bug in the Javascript. I have found some of the minor looking issues to completely kill the functioning of the server. Minor things like namespace bugs or variable type bugs.  Not to discount the issue. Since I have had major hair pulling sessions over this. But really what is needed is a better or more complete logging system to tell when and why the server died.

**Comment by AlistairBates** [comment]
Thanks for replying @erlicthemad 

I agree entirely. That's really what issue #244 is about. It's very frustrating when the Wakanda service looks like it's running from the service interface but a minor issue has stopped it.

This is a different issue as the Wakanda server runs successfully when I downgrade to Ubuntu 16.04.

**Comment by AlistairBates** [comment]
Any update on this. Seems not to be fixed in v2.5.0

**Comment by JegoYann** [comment]
Hello @AlistairBates ,

This is planned for the v2.6.0 release.
https://trello.com/b/RA1yHvUU/wakanda-roadmap

**Comment by JegoYann** [comment]
Wakanda `v2.6.0` now integrates `systemd` and fixes all known issues on service start/stop.
Do not hesitate to reopen if something's wrong.
