### ISSUE TITLE
Wakanda Enterprise Admin Page empty

### ISSUE THREAD

**Issue by ronpfi** [Wakanda/wakanda-issues#256]
Wakanda Enterprise has an admin page based on the (old) WAF - "WAF" content seen when investigating the source of the page. But my browser window remains empty - the content isn't been rendered.

Wakanda Enterprise 2.5.0 - macOS 10.13.4 - Chrome 66.0.3359.181

**Comment by erlicthemad** [comment]
I have been seeing this issues since version 2.3.0 When the project is running you could not log in to the admin page. It used to be that after the project started the https page stopped working as it was serving the project. But now even when I connect to the localhost HTTP port it will die when it gets to the authentication screen. This occurs on any web browser, Safari, Chrome, and Firefox. I too am running the enterprise version of Wakanda server.

**Comment by kirkroyster** [comment]
My experience is that you have to hit refresh after the blank screen and then it will display.

**Comment by JegoYann** [comment]
Hello @ronpfi ,
The old admin page is not there anymore. You need to navigate to http://127.0.0.1:8080/admin/ for the new one.

https://wakanda.github.io/doc/#/guide?section=main-prod
