### ISSUE TITLE
Angular-Wakanda and privilleges for "describe"

### ISSUE THREAD

**Issue by ronpfi** [Wakanda/wakanda-issues#45]
For me there is an error thrown if you have a public class and no privileges for "describe" for this class. Obviously Angular-Wakanda generates by init this request (and result) "http://127.0.0.1:8000/rest/$catalog/$all/ Failed to load resource: the server responded with a status of 401 (Unauthorized)"

**Comment by mrblackus** [comment]
Hi,

`describe` privilege is needed for Angular-Wakanda to correctly works because, as you stated, it relies on `rest/$catalog` service. You must set it to `public` or a specific group. In that last case, you must call `$login` before calling `$wakanda.init()`, so that you have the right permission to have that particular dataClass description.
