### ISSUE TITLE
lot of problems with wakanda-server on linux

### ISSUE THREAD

**Issue by citron** [Wakanda/wakanda-issues#49]
Hello

I do use wakanda since 2013. My application was running fine from 2013 up to november 2015 when Wakanda SAS published the "disruption" package. 
I had to change a lot of details to convert my application to the new standards and get rid of the old widgets. 
But now I do have another big problem. I develop on OSX and I do use a linux server for production. Everything runs pretty well on OSX but the same application crashes wakanda-server on linux. First of all, it seems that the Authentification does not work anymore. After a crash, when I try to restart the server, I get messages like "Failed to integrate journal" and "Cannot open the datastore".

The problem is that I simply don't know why. The logs are insufficient to understand the reasons of the failures. 

Are there any tools to diagnose an app or a database? Is there any magic word that can increase verbosity of wakanda-server?
From my point of view, I feel like wakanda-server on linux is about to die because of Wakanda SAS cloud business. Am I right?

**Comment by hamzahik** [comment]
Hello @citron 
In order to analyse your problem more details are needed.

- What do you mean by 

> the same application crashes wakanda-server on linux

Does this happen after doing a specific action on the application ? 

- What do you mean when you say 

> the Authentification does not work anymore

To respond to your thought : 

> From my point of view, I feel like wakanda-server on linux is about to die because of Wakanda SAS cloud business. Am I right?

It this actually the opposite, the Wakanda managed server hosting uses Linux servers (Ubuntu) it means we consider Linux a priority production environnement for Wakanda apps and so we give more attention to the quality of the server on Linux.

**Comment by hamzahik** [comment]
@citron I'll close the issue for now since we don't have enough information to help you fix the problems in your deployment. Don't hesitate to re-open it and add more details so we can help you.
