### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by ronpfi** [Wakanda/wakanda-issues#57]
Hi, why is there Release 1.0.3 after 1.1.0?

**Comment by hamzahik** [comment]
Hello,

We have detected a bug on the studio that was not found during the validation process. So we decided to put the 1.0.3 back on the website to avoid user frustration. The 1.1.0 is still available on github as a pre-release.
Sorry for the inconvenience.

**Comment by alcada** [comment]
Hello

How can I download the pre-releases and nightly builds.
I used to access the address
http://download.wakanda.org/DevChannel/Main/Wakanda/
to test bug corrections but since March (Linux), February (windows) and January (Mac) that stop the succession of builds.

Thanks

Luís Alçada
Coimbra University
Portugal

**Comment by hamzahik** [comment]
Hello @alcada,

The pre-release is now available directly from the [website](https://wakanda.github.io). But as a general rule all available builds are listed on this [page](https://github.com/Wakanda/wakanda-digital-app-factory/releases).
