### ISSUE TITLE
ng-wak: Query filter is truncated when using '#'

### ISSUE THREAD

**Issue by JUX84** [Wakanda/wakanda-issues#62]
Hello,

I guess the bug came along the v1.1.0 update.

Here's my filter:
![capture d ecran 2016-05-12 a 10 26 28](https://cloud.githubusercontent.com/assets/3422399/15208571/a84bda82-182c-11e6-9b76-ff589fb3434a.png)

And then, when the request is made, the filter stops right at the '#':
![capture d ecran 2016-05-12 a 10 26 55](https://cloud.githubusercontent.com/assets/3422399/15208579/b85b9cf0-182c-11e6-9591-70f7b7f3dc99.png)

Regards.

**Comment by mrblackus** [comment]
Hi @JUX84,

Thanks for the report. Can you provide me the original `option` object given as a parameter to the `query()` call?

**Comment by JUX84** [comment]
Hi @mrblackus,

Thanks for the quick answer.

Here are my `target, option` parameters:
![capture d ecran 2016-05-12 a 10 50 39](https://cloud.githubusercontent.com/assets/3422399/15209078/732de2de-182f-11e6-9ff9-006ee4d9cfc1.png)

BTW replacing '#' by '!=' works.

**Comment by mrblackus** [comment]
Thanks, I investigate on that and come back to you soon. ;)

**Comment by JUX84** [comment]
Thank you!

**Comment by mrblackus** [comment]
@JUX84 Just to be sure, on your `filter`, there is `PRF_Video_Level#999`.
Is it a field named `PRF_Video_Level#999`, or are you using the `#` operator between field `PRF_Video_Level` and value `999`?

I am asking that because `#` operator is not supposed to be used on REST API (and so on frontend clients like Angular-Wakanda), it's only a SSJS operator.
If you are using it as an operator, it should be replaced by `!=` one.

**Comment by JUX84** [comment]
It _is_ an operator.

Ok that's what I was thinking.

It worked before, and it's the 4D way so I kept it like this.

Then the issue is resolved. Maybe you should add an example in the documentation because the only available examples use `=, <, >`

Thank you ;)

**Comment by mrblackus** [comment]
Sure, we will add such an example on the documentation.

Thanks
