### ISSUE TITLE
relation problem in my ionic project

### ISSUE THREAD

**Issue by znodal** [Wakanda/wakanda-issues#68]
I got a problem working with releations and ionic

I created a data model and added a releation:
![screen1](https://cloud.githubusercontent.com/assets/18338145/15427397/1ba0bf16-1e95-11e6-9362-eb174ab0ba1b.jpg)
in the data browser included in wakanda it all looks like I want it to work:
![screen2](https://cloud.githubusercontent.com/assets/18338145/15427399/1ba66d12-1e95-11e6-9964-3d20419a59a6.jpg)
but when I trying to get it running in my ionic project there seams to be no releation between my 2 classes .. also the reverse tell me "owner: null"
![screen3](https://cloud.githubusercontent.com/assets/18338145/15427398/1ba348bc-1e95-11e6-9a5b-8cf8c00a15ea.jpg)
thats the code I'm using:
![screen4](https://cloud.githubusercontent.com/assets/18338145/15427400/1ba6a6c4-1e95-11e6-982d-f5901c9726e2.jpg)

I hope I'm not complety wrong posting this kind of problem here, but I don't find any other place to do so .. 
any help would be appreciated .. tnx :)

**Comment by issameljohri** [comment]
Hello @znodal,
In order to retrieve the value of related attribute you have to use $fetch().
[http://doc.wakanda.org/home2.en.html#/Angular-Wakanda/Entity/fetch.301-1072167.en.html](url)

`ds.Users.$find(currentUser.ID).$promise.then(function(event){
  		$scope.user = event.result;
                $scope.user.paymentsCollection.$fetch();
  		console.log(JSON.stringify(event.result));	
  	})`

**Comment by znodal** [comment]
hi @issameljohri .. works perfect .. thank you very much :)

**Comment by issameljohri** [comment]
You are welcome :)
