### ISSUE TITLE
Inconsistent loading from local wakanda server

### ISSUE THREAD

**Issue by maeruu** [Wakanda/wakanda-issues#77]
### Problem
My problem/bug (i don't really know sorry...) is that sometimes randomly i don't get any data from the server. I just get an error in the console and the request failed. But this happens only in 10-20 reloads/loads and if i just reload it is gone and it works again. But I can't say my customer "just press F5"...
Is it a bug or did I just use something wrong?
Console:
![consoleerror](https://cloud.githubusercontent.com/assets/12249502/16003451/fa46d136-315c-11e6-9799-6eb0ddc30faf.png)

Response:
![response](https://cloud.githubusercontent.com/assets/12249502/16003414/c2fb5b3e-315c-11e6-807f-969488a0a383.png)

### Setup
My Setup is a local wakanda server which comes from wakanda enterprise studio (Wakanda Enterprise Studio 11 build 11.196912) behind that is a 4D-Database(I get that from somewhere else so I know little about it).
I use Angular-Wakanda v1.0.4 -> Angular v1.4.3 and i work on an app so ionic is also in there.
I'm working on windows 10.
If you need more information just ask.

### My Code
**Server Side:**
```
model.someTestTable.methods.getTaetigkeiten = function() {
	var params = { "BetriebId": sessionStorage.betriebId };
	return ds.s1_Taetigkeit.waka_wtr_Taetigkeiten_Get(params);
};
```
**Client Side in a service/factory:**
```
var getAllTaetigkeiten = function(){
	loadingAnimation.increase();
	return ds.s1_Taetigkeit.getTaetigkeiten().$promise.then(function(evt){
		if(evt.result != null || evt.result != undefined){
			loadingAnimation.decrease();
			return $wakanda.$transform.$objectToCollection(evt.result).map(TaetigkeitDto);
		}
	});
}
this.getAllTaetigkeiten = getAllTaetigkeiten;
```
**Usage in a controller:**
```
timeTrackingModalService.getAllTaetigkeiten().then(function(r){
	$scope.taetigkeiten = r;
	$scope.record.taetigkeit = $filter('filter')(r, record.Taetigkeit_ID, true)[0];
});
```

**Comment by hamzahik** [comment]
Hello @maeruu,

Please activate the debugger and try to reproduce the bug again. 
- Activate the debugger
![image](https://cloud.githubusercontent.com/assets/6703912/16070682/67e5b240-32d7-11e6-9137-59ca257003ae.png)

You'll then be able to debug your code and see what's wrong 

![image](https://cloud.githubusercontent.com/assets/6703912/16070962/030ae4ce-32d9-11e6-8c79-1bd7b37edcf4.png)
**Pay attention that the remote debugger only works on Google Chrome**
if the debugger page is currently open in a browser other than Chrome you should close it and open the following URL on chrome `http://127.0.0.1:8080/debugger`. If you are using another administration port you should use it instead of `8080`.

If for some reason the debugger does not show up, try the following : 

```javascript
model.someTestTable.methods.getTaetigkeiten = function() {
    var params    = { "BetriebId": sessionStorage.betriebId };

    try {
        var response = ds.s1_Taetigkeit.waka_wtr_Taetigkeiten_Get(params);
    } catch(e){
        return "error : " + e.toString();
    }

    return response;
};
```
Hope this helps !

**Comment by hamzahik** [comment]
@maeruu I will close the issues for now. But don't hesitate to re-open it if you're still facing the same issue.

**Comment by maeruu** [comment]
Hi @hamzahik
I already did that but i can't find any solutions... and the debugger just says **"A remote request to host: "local wakanda Serverip" has failed"** and I have no clue why.

**Comment by hamzahik** [comment]
@maeruu can you watch this [video](https://www.youtube.com/watch?v=ReW_U05ZXtk) and tell me if you are doing the same

**Comment by maeruu** [comment]
@hamzahik i'm doing the exact same thing. but i worked around now it should not happen anymore. since it happens just once in a while i can just try it again if it fails again, i log an error.
