### ISSUE TITLE
Wak 11 v1.1.0.b - Error adding project to solution

### ISSUE THREAD

**Issue by alcada** [Wakanda/wakanda-issues#81]
Hello

When you create a new fresh solution in wakanda studio (with "add a blank project to the new solution" checked), if you decide latter to add a new (second) project to the same solution, you alloys get the new solution dialog instead of a new project dialog.
Steps:
1-create a new solution "a"
2-right click "SOLUTION: a" and chose "New->Project)
3-The new solution dialog appear (in Studio v1.0.3 the correct new project dialog appear)
Now I can't manage to add a second project to an existing solution.

Regards
Luís Alçada
Coimbra University

**Comment by jonathanargentiero** [comment]
Hello @alcada,
I think I've got your issue. The fact is in the latest version of templates extensions the "add a blank project to the new solution" is no more and the solution and project dialogs are almost identical.

Therefore I suspect that in your `Documents\Wakanda\Extensions` folder you have another version of the `wakanda-extension-templates` extension that overrides the newer one packaged in Wakanda Studio.

While using alpha/beta version we don't update Github repositories yet, thus Wakanda Extensions tends to downgrade themselves or doesn't detect the different versions packaged.

In the near future we will release an Addons version smart enough to deal with this kind of issues but for the moment you should be patient and remove the old version in order to let the Studio charge the new one packaged.

**Comment by alcada** [comment]
OK. If I do not upgrade the extensions after erasing the oldest in my home folder, both issues (80 and 81) cease to exist.
Thank you.
