### ISSUE TITLE
Totally and absolutely confused.

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#87]
I have been using Wakanda for more than two years now. We are using an Angular2 front end and haven't used the javascript client yet.

However I am now totally and absolutely confused about the status of Wakanda and where to get information.

Here are some of the things I am finding confusing:

- How do I know if I am running the latest version of Wakanda? Up until version 11 it was pretty clear but now I have no idea.
- How does version 11 relate to v 1.0.0?
- What are the differences between the community and enterprise editions? There used to be a comparison table on your website which was really useful but that's gone now.
- For a new user coming in it is not immediately apparent there are two editions.
- I just realised yesterday that the '.org' site is for the community edition and the '.io' site is for the enterprise edition. This is not at all clear. I have no idea how someone new to Wakanda would have any chance of getting an overview of Wakanda and its variants and the resources available.
- I just found out yesterday (or perhaps the day before) that this is where I can report bugs. It is not at all clear from your web presence that this is the case.
- What on earth is the 'Digital App Factory'? When this phrase first appeared I wondered if this was a new variant or some sort of superset of Wakanda. Can you please be consistent with naming.
- I downloaded the 'Pre-release with Angular2 and Ionic2 support' a few weeks ago but couldn't find anything in it referring to Angular 2.
- The 'Help' menu in Wakanda takes me to 'doc.wakanda.org' but now I find there is also a 'livedoc.wakanda.org' which is different to the one I have been using.

**Comment by chriscurnow** [comment]
Oh, just rereading this I'd like to say I love Wakanda and think you guys have done a fantastic job. I just wanted to say I don't think you could have done a better job of communicating the changes you have made since December 2015. A lot of stuff just came out of the blue and, as a Wakanda developer, I have been left confused. There are also some things I think you need to clarify on your websites. Get this all rights and we'll be cooking with gas again.

**Comment by hamzahik** [comment]
Hello @chriscurnow and thank you for your feedback.

I'll try to answer your questions and please do ask for more information if it isn't clear enough.

> How do I know if I am running the latest version of Wakanda? Up until version 11 it was pretty clear but now I have no idea.

Same as in previous versions : `Help` > `About Wakanda Studio`

![image](https://cloud.githubusercontent.com/assets/6703912/16900014/bf2aaa5c-4c17-11e6-928f-aa56342dad56.png)
Compare it to the version on the website.

![image](https://cloud.githubusercontent.com/assets/6703912/16900088/2acee71c-4c1a-11e6-8b2e-1875ee7e5b5f.png)

I'm using the 1.1.0 pre-release as you can see. (not a stable release yet)

You can also visit [this](https://github.com/Wakanda/wakanda-digital-app-factory/releases) page where you can have more details : latest stable release, latest pre-release, server and studio change logs..

> How does version 11 relate to v 1.0.0?

Wakanda versioning system has changed to simplify the migration decision for end users. We have adopted [semver](http://semver.org). v11 is the version 1.0.0
Simply put a version is in the format `a.b.c` , if only `c` changes this means you should migrate with zero changes to your app. If `b` changes this means new features/enhancements are available but no migration steps are needed. If `a` changes you should expect breaking changes and you might need to follow migration steps in order to use the new release. That said, it is always a good idea to read the release notes.

> What are the differences between the community and enterprise editions? There used to be a comparison table on your website which was really useful but that's gone now.

You can checkout the [pricing page](http://www.wakanda.io/pricing). A comparison table is being prepared with the updated information.

> For a new user coming in it is not immediately apparent there are two editions.

> I just realised yesterday that the '.org' site is for the community edition and the '.io' site is for the enterprise edition. This is not at all clear. I have no idea how someone new to Wakanda would have any chance of getting an overview of Wakanda and its variants and the resources available.

> I just found out yesterday (or perhaps the day before) that this is where I can report bugs. It is not at all clear from your web presence that this is the case.

We have links on the community website pointing to the enterprise version and vice versa. We don't want to push the commercial version too much. But the documentation as well as the change logs state when a feature is available only on the enterprise release.

![image](https://cloud.githubusercontent.com/assets/6703912/16900110/3a6b1316-4c1b-11e6-8d97-502bf0224f2c.png)

![image](https://cloud.githubusercontent.com/assets/6703912/16900111/50048b6c-4c1b-11e6-8358-47b897618114.png)

![image](https://cloud.githubusercontent.com/assets/6703912/16900121/765a9162-4c1b-11e6-9ac6-9159b17eb46b.png)

> What on earth is the 'Digital App Factory'? When this phrase first appeared I wondered if this was a new variant or some sort of superset of Wakanda. Can you please be consistent with naming.

You don't need to worry about that, it is the same product.

> I downloaded the 'Pre-release with Angular2 and Ionic2 support' a few weeks ago but couldn't find anything in it referring to Angular 2.

Since it is a pre-release, the getting started guide was not updated yet. But if you try to create a new app you'll see this : 

![image](https://cloud.githubusercontent.com/assets/6703912/16900135/fe747b1c-4c1b-11e6-906f-0bbe45a6dcfa.png)

You can customize what technology you want to use for the web and mobile part of your application. The studio will install the dependencies for you, starts live reload, gives you completion for TypeScript and JavaScript files using Angular2..

> The 'Help' menu in Wakanda takes me to 'doc.wakanda.org' but now I find there is also a 'livedoc.wakanda.org' which is different to the one I have been using.

Yes we are aware of the problem of multi-site documentation and we are working on making things more simple and coherent.

It'll be a good idea to subscribe to the wakanda mailing list, this way you can stay up-to-date about Wakanda. The usage of Github Issues for bug reporting, StackOverflow for technical help, Professional Support and services and more were announced in the newsletter. Scroll to the bottom of the wakanda.org website to see the form (We should probably make it more obvious 💡).

**Comment by chriscurnow** [comment]
@hamzahik – thanks so much for your detailed responses above. That's cleared up a lot and it's great to know I can get answers now. If it's OK with you, I will respond with separate issues so it's easier to follow.
